### ISSUE TITLE
Whishlist: set bibliographyLocale in the wordprocessors' plugin-ui on a per document basis

### ISSUE THREAD

**Issue by ronalde** [zotero/zotero-libreoffice-integration#15]
Following [extensions.zotero.export.bibliographyLocale should default to environments locale #600](https://github.com/zotero/zotero/issues/600), it would be nice if the `bibliographyLocale` could be set in the wordprocessors' plugin-preferences-ui, on a per document basis, defaulting to the documents (general) language.

**Comment by simonster** [comment]
This is the wrong repository for this issue (the code is in Zotero itself, not the LibreOffice plugin), but there is some discussion in zotero/zotero#623.
