### ISSUE TITLE
Not working with 64-bit jre (and consequently 64-bit LO)

### ISSUE THREAD

**Issue by andersjohansson** [zotero/zotero-libreoffice-integration#19]
"We've pretty consistently seen the LibreOffice add-on not working with 64 bit JRE versions" @adam3smith, [here](https://forums.zotero.org/discussion/51023/zotero-firefox-plugin-error-with-libreoffice-5/).

If that is the case, is this a bug that can be fixed?

I consider this a major problem. I'm using a 64-bit linux system and have been doing so for years. While with multiarch I can install 32-bit versions of libreoffice + java (since I can't use 32-bit java in the standard 64-bit LO) I find this a hassle.

I remember everything working for me a few months back (with some kind of trouble, but everything 64-bit I guess) but now when I tried with LO 5.0.5.2 and some different JREs (all 64-bit), nothing happens when clicking the buttons.

**Comment by andersjohansson** [comment]
Perhaps this information should at least be added to the troubleshooting page?
https://www.zotero.org/support/word_processor_plugin_troubleshooting

**Comment by adam3smith** [comment]
(this isn't a confirmed bug, and very likely not a Zotero bug at all. Please close here for the time being and move back to the forum and we can discuss it more. As you can see in that thread, I was clearly wrong about it not working with 64-bit JREs. I actuall have Zotero working in LibreOffice on 64-bit Ubuntu with the 64-bit Java 8 from Oracle ).

**Comment by andersjohansson** [comment]
Oh, sorry for the noise then. Didn't read the thread carefully enough and will test some more.

**Comment by adam3smith** [comment]
(jsut to be clear: I'm not saying that all is dandy with LO integration. I'm certainly happy to add things we're sure about to the troubleshooting and it's possible there's something fixable on the Zotero side. It's just as this point to unclear what the exact parameters are to be useful in a bug tracker).
