### ISSUE TITLE
Portable

### ISSUE THREAD

**Issue by dandar** [zotero/zotero-libreoffice-integration#20]
Many use portable apps firefox and libreoffice.  Make this extension compatible by:
1. When JRE not installed, try to use Java runtime that comes with libreoffice, if cannot find libreoffice, then ask for path from user and provide some guidance/link to online wiki.
2. Offer option to use portable apps Jportable (java runtime portable version)

**Comment by adomasven** [comment]
This tracker is for developer use only. Please post feature requests on Zotero forums.

Overall, LibreOffice, different OSes and JVMs are brittle as they are and often don't play nice together. We are already covering a huge surface area supporting those and accommodating portable installs is yet another beast. Moreover, Zotero is essentially a LibreOffice client supplying the extension and relying on the existing JVM in the LibreOffice, so this is not really something that we should or can adequately address.
