### ISSUE TITLE
Zotero's integration to Libreoffice on Fedora Linux does not respond

### ISSUE THREAD

**Issue by lejocelyn** [zotero/zotero-libreoffice-integration#23]
Zotero works well either as a plugin for Firefox or as a standalone but the integration to Libreoffice does not respond.
Similar to this issue : 
https://forums.zotero.org/discussion/37778/not-responding/

I thought it might be a problem with Java but I can't get any error message so I don't know. The issue is the same whether I try with the addon or the standalone.

**Comment by adomasven** [comment]
Sorry it took a while to respond. The issue tracker is for developer use only, please use Zotero Forums for support requests.
