### ISSUE TITLE
Warn about JRE on macOS

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-libreoffice-integration#27]
The JDK requirement on macOS is now a lot more problematic with Zotero 5, because there's no way anyone would know they need that (whereas before everyone on Z4Fx had the warning on the download page). Do we know what the actual issue is with this? If we can't work around it, can we detect the Java version and show a warning in the Cite prefs rather than trying to install a broken extension?

**Comment by adomasven** [comment]
5.0 doesn't really change anything regarding the requirement for JDK. But we definitely can and shoud do more in the client.

When talking to libreoffice devs this is the [response](http://narkive.com/89EXQgBf.4) I received:

> See <https://wiki.documentfoundation.org/ReleaseNotes/5.1#OS_X>:
> 
> "New Issue: LibreOffice on OS X now requires installation of an Oracle
> Java JDK for use of Base (HSQLDB) or any extensions authored in Java
> (e.g. NLPSolver).
> 
> "Prior work arounds of having both an Apple JRE 6 and an Oracle JRE 8
> are no longer sufficient. Use of the JDK is now hard coded, see
> tdf#74877, tdf#94716 and core commit
> 32bc8ddbf335dd26019edcf12758643b4cff9913."
> 
> I'm not aware of a bug filed nor anybody actively working on making
> detection of Oracle JRE (when Apple JRE is also installed, to make the
> Oracle JRE usable) work again. Seems more like everybody at LO's end is
> sitting on their hands waiting for Oracle to fix their JRE bug, so we
> can eventually revert that detect-JDKs-only fix-for-now.

**Comment by dstillman** [comment]
> 5.0 doesn't really change anything regarding the requirement for JDK.

Yes, it does, because everyone on Zotero for Firefox had to download the plugin from our download page, where we warned about this.
