### ISSUE TITLE
RTF insertion on macOS does not work

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-libreoffice-integration#35]
LO 5.3.0.3, macOS 10.13.2

**Comment by adomasven** [comment]
Cannot reproduce after updating extension in LO to 5.0.8

**Comment by dstillman** [comment]
I'm still seeing this with 5.0.8. Was happening in 5.3, still happening in 5.4.4.2.

The properly formatted version appears initially (maybe without a gray background?) and then is immediately replaced by a field with a gray background and no formatting.

1. Add a citation in Chicago.
2. Click on the citation and choose Add/Edit.
3. Open Classic View, Show Editor
4. Add italics to a word in the citation

The italics don't appear in the document. If you return to the editor, the formatting is still set.

**Comment by adomasven** [comment]
This is just the editor styling not actually functioning. It produces HTML formatting, but all of our plugins use RTF.

**Comment by dstillman** [comment]
If it's not functioning, why am I briefly seeing the correct formatting in LibreOffice, and why did it just appear when I clicked Refresh a couple times?

Let's leave this open until this is resolved.

**Comment by dstillman** [comment]
1. Add a citation in Chicago, ReferenceMarks.
2. Click on the citation and choose Add/Edit.
3. Open Classic View, Show Editor
4. Add an underline to a word in the citation and click OK.

The underline doesn't appear for me in LibreOffice.

However:

5. Click Refresh

I briefly see the underline, and then it goes away again.

6. Click Refresh again.

The underline reappears and stays put.

**Comment by adomasven** [comment]
Ok. Should have got the sleep before looking into this:

- Custom citation code is broken in https://github.com/zotero/zotero/pull/1242 . To be fixed.
- Custom citations work fine on master with all word processors. HTML -> RTF conversion done by [styled-textbox](https://github.com/zotero/zotero/blob/master/chrome/content/zotero/bindings/styled-textbox.xml)
- There's a caveat for LibreOffice plugin, where partial inline citation styling disappears and only styling applied to the whole chunk of text applies. This is due to an [optimization](https://github.com/zotero/zotero-libreoffice-integration/commit/2deea6bd46b50f72cdc937a468e88ab6cd4461ad), which speeds up inline style updates for libreoffice 2x. I'm not in favor of reverting this until someone on the forums comes with a very compelling argument for why partial custom styling of inline citations is *that* important

Inclined to close this.

**Comment by adomasven** [comment]
Closing this since I don't see us slowing down the LO plugin to facilitate an extreme corner case and there has been no discussion re this for 2 years on the forums or anywhere else
