### ISSUE TITLE
Possible regression at 602e1e ?

### ISSUE THREAD

**Issue by fbennett** [zotero/zotero-libreoffice-integration#40]
With 602e1e adopted, under Linux, running a Juris-M Standalone build, opening a blank document in LO, entering one citation, and then entering a bibliography yields an error, "json.properties is undefined". After removing 602e1e, the same operation clears without error. (Juris-M uses the Zotero word processor plugins without modification.)

**Comment by adomasven** [comment]
Whoops, sorry about that. Fixed in cdcf2b34e5e1f0d76df2449e897613a5c8ab8911, thanks for reporting.
