### ISSUE TITLE
Update JDK requirement on macOS?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-libreoffice-integration#44]
https://forums.zotero.org/discussion/78018/unable-installing-the-libreoffice-integration-due-to-java

JDK 8 has become much more annoying to download — it now requires an account. Are the requirements here still the same, or might this now work with a newer Java and/or a JRE build?

**Comment by adomasven** [comment]
Newest JDK works fine. The JRE still doesn't work. I've updated the docs and responded on the thread. I post the relevant [LibreOffice bug](https://bugs.documentfoundation.org/show_bug.cgi?id=101956) here, although it's unclear when, if ever this gets fixed. I'll close the issue for now.
