### ISSUE TITLE
Remove Zotero wiki dev documentation?

### ISSUE THREAD

**Issue by bwiernik** [zotero/zotero-libreoffice-integration#55]
It seems like the REAMDE in this repository has largely replaced the getting started instructions described on the Zotero support wiki: 
https://www.zotero.org/support/dev/client_coding/libreoffice_plugin_wire_protocol

Can/should the support wiki page be removed?

**Comment by adomasven** [comment]
The README.md here is about developing the LO plugin. The wiki page is specifically about the wire protocol (which is part of the LO plugin, but also could be implemented by another word processor plugin), so neither supersede the other
