### ISSUE TITLE
IEEE Refrence style does not show correctly in libreoffice with two column veiw

### ISSUE THREAD

**Issue by WalJT** [zotero/zotero-libreoffice-integration#58]
This seems to be an old issue, which may be related to #12. To reproduce:

1.  Create a LibreOffice writer document in two column format (I am using Liberation Serif 10pt font)
2. Insert a citation using the Zotero addon with IEEE referencing style
3. Insert a bibliograpy

A screenshot of the results:

![Screenshot_20201214_113603](https://user-images.githubusercontent.com/50880589/102077752-b35c6b80-3e01-11eb-878a-077486550993.png)

My software versions are:

- Zotero 5.0.93
- LibreOffice 7.0.3.1
- Operating system is Ubuntu 20.04 if it matters.

**Comment by adomasven** [comment]
I cannot seem to reproduce this in a new document with LibreOffice 7.0.3.1. Either way, Zotero generally does not use the Github issues for user bug reports. See https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

Please create a thread on the Zotero forums with full steps on how to reproduce this in a new document.
