### ISSUE TITLE
how to use a libreoffice text style

### ISSUE THREAD

**Issue by Thorgrimson** [zotero/zotero-libreoffice-integration#61]
I'm not shure if this is even possible, if not this will be a feature request.

I want  to insert citations from zotero with a libreoffice text style to make it possible to change the style later or just use from start automatically a diffrent font style/size as in stadard text.

in the moment the citations reference came without a text style.

**Comment by adomasven** [comment]
Please post all Feature Requests to [Zotero Forums](https://forums.zotero.org).

This is probably possible as a child style of the Normal style, but we would need to see if there is more support (on the Forums) before we consider it since it's not an entirely simple thing to implement.
