### ISSUE TITLE
Disable track changes when inserting/editing citations

### ISSUE THREAD

**Issue by adomasven** [zotero/zotero-libreoffice-integration#63]
See https://api.libreoffice.org/docs/idl/ref/servicecom_1_1sun_1_1star_1_1text_1_1GenericTextDocument.html#a6649fa1a4963f78b9d70a85edef770e4 for API docs

**Comment by raffaem** [comment]
I came up with:
```
XPropertySet docPropSet = UnoRuntime.queryInterface(XPropertySet.class, textDocument);
boolean recordChanges = (Boolean) docPropSet.getPropertyValue("RecordChanges");
docPropSet.setPropertyValue("RecordChanges", false);
```

but I don't know where to put it.

Looks like Document::insertMarkAtRange is not the correct place, as it is called right after you click "Add/Edit Citation", and not when the citation is actually added.
