### ISSUE TITLE
Copy-paste citation lose ReferenceMark

### ISSUE THREAD

**Issue by 875d** [zotero/zotero-libreoffice-integration#75]
Is it normal that when I copy-paste a citation, I lose the reference mark and only the text is copied?

**Comment by adomasven** [comment]
Please post all feature requests and bug reports to the [Zotero Forums](https://forums.zotero.org). See [CONTRIBUTING.md](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md) and [How Zotero Support Works](https://www.zotero.org/support/zotero_support) for more info.

This is an upstream issue in LibreOffice and the way ReferenceMarks are implemented. Unfortunately there is no solution.
