### ISSUE TITLE
Include link to extension in documentation

### ISSUE THREAD

**Issue by errotu** [zotero/zotero-libreoffice-integration#77]
I had to install the LibreOffice word processor plugin manually (because I am using LibreOffice Portable) and was unable to do so via the route [described in the documentation](https://www.zotero.org/support/word_processor_plugin_manual_installation#libreoffice). For some reason, trying to install the file from the Zotero folder on my hard disk always threw an error.

Maybe it's a possible alternative to include [this link to the file in the Github repository](https://github.com/zotero/zotero-libreoffice-integration/raw/master/install/Zotero_OpenOffice_Integration.oxt) (or even replace the rather complicated directions in the documentation with it)? It worked like a charm with that one.

**Comment by adomasven** [comment]
All feature requests and bug reports should be posted on Zotero Forums. See https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

> Maybe it's a possible alternative to include [this link to the file in the Github repository](https://github.com/zotero/zotero-libreoffice-integration/raw/master/install/Zotero_OpenOffice_Integration.oxt) (or even replace the rather complicated directions in the documentation with it)?

Certainly not. Often this points to a file that has not been released yet, or is only available on the beta version of Zotero and may break integration in various ways for users. On the other hand the file packaged with Zotero is always some (older) version of this file, so in terms of installation success both should either work or fail. Are you sure you didn't do some other troubleshooting in between (like installing/tweaking Java), that would have fixed the plugin installation into LibreOffice?
