### ISSUE TITLE
Tabbed View: Where do I find Zotero?

### ISSUE THREAD

**Issue by kaffeeringe** [zotero/zotero-libreoffice-integration#80]
Hi!

I wanted to switch the view in LibreOffice to "tabbed" - so help new users to get into it:
https://www.howtogeek.com/788591/how-to-make-libreoffice-look-like-microsoft-office/

But I don't find the Zotero icons in that view. I though they were in the extensions tab, but that is empty.

**Comment by adomasven** [comment]
Please post all support questions to [Zotero Forums](https://forums.zotero.org/).

Zotero is not available as a tab in LibreOffice. See discussion https://github.com/zotero/zotero-libreoffice-integration/issues/46
